CREATE TABLE DONDATHANGG (
    SOHOADON         VARCHAR(10),
    MAKHACHHANG      VARCHAR(50),
    MANHANVIEN       VARCHAR(50),
    NGAYDATHANG      VARCHAR(100),
    NGAYGIAOHANG     VARCHAR(50),
    NGAYCHUYENHANG   VARCHAR(15),  
    NOIGIAOHANG      VARCHAR(15),
    PRIMARY KEY  (SOHOADON)
);