CREATE TABLE MATHANG 
(
	MAHANG CHAR(15) PRIMARY KEY,
	TENHANG VARCHAR(50) NOT NULL,
	MACONGTY CHAR(15) NOT NULL,
	MALOAIHANG VARCHAR(10) NOT NULL,
	SOLUONG INT CHECK (SOLUONG>=0),
	DONVITINH VARCHAR(20) NOT NULL,
	GIAHANG FLOAT CHECK (GIAHANG>=0)
);