CREATE TABLE NHACUNGCAP
(
	MACONGTY CHAR(15) PRIMARY KEY,
	TENCONGTY VARCHAR(50) NOT NULL,
	TENGIAODICH VARCHAR(50) NULL,
	DIACHI VARCHAR(50) NOT NULL,
	DIENTHOAI VARCHAR(11) NOT NULL,
	FAX VARCHAR(10) NULL,
	EMAIL VARCHAR(50) NOT NULL
);