CREATE TABLE CHITIETDATHANG (
      SOHOADON        INT,
      MATHANG         VARCHAR(50),
      GIABAN          DECIMAL(10,2),
      SOLUONG         INT,
      MAGIAMGIA       VARCHAR(20),
     PRIMARY KEY  (SOHOADON, MATHANG)
);